# Generated by Django 5.1.6 on 2025-02-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jumlah_uang', models.IntegerField(default=0)),
                ('history', models.TextField(blank=True, default='')),
            ],
        ),
    ]
